# Create a new product
mutation CreateProduct(
  $productID: String!
  $productSlug: String!
  $name: String!
  $description: String!
  $price: Float!
) {
  product_insert(
    data: {
      productID: $productID
      productSlug: $productSlug
      name: $name
      description: $description
      price: $price
      nameEmbedding_embed: { model: "textembedding-gecko@003", text: $name }
      descriptionEmbedding_embed: { model: "textembedding-gecko@003", text: $description }
    }
  )
}

# Update an existing product
mutation UpdateProduct(
  $id: UUID!
  $name: String!
  $description: String!
  $price: Float!
  $productID: String!
  $productSlug: String!
) {
  product_update(
    key: { id: $id }
    data: {
      name: $name
      description: $description
      price: $price
      productID: $productID
      productSlug: $productSlug
      nameEmbedding_embed: { model: "textembedding-gecko@003", text: $name }
      descriptionEmbedding_embed: { model: "textembedding-gecko@003", text: $description }
    }
  )
}

# Delete a product
mutation DeleteProduct($id: UUID!) {
  product_delete(key: { id: $id })
}

# Create a new review
mutation CreateReview(
  $productID: String!
  $productSlug: String!
  $productName: String!
  $userID: String!
  $userName: String!
  $rating: Float!
  $content: String!
) @auth(level: PUBLIC) {
  review_insert(
    data: {
      productID: $productID
      productSlug: $productSlug
      productName: $productName
      userID: $userID
      userName: $userName
      rating: $rating
      content: $content
      contentEmbedding_embed: { model: "textembedding-gecko@003", text: $content }
    }
  )
}

# Update an existing review
mutation UpdateReview($id: UUID!, $rating: Float!, $content: String!) @auth(level: USER) {
  review_update(
    key: { id: $id }
    data: {
      rating: $rating
      content: $content
      contentEmbedding_embed: { model: "textembedding-gecko@003", text: $content }
    }
  )
}

# Delete a review
mutation DeleteReview($id: UUID!) @auth(level: USER) {
  review_delete(key: { id: $id })
}
