// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: envoy/config/core/v3/extension.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Any } from "../../../../google/protobuf/any.js";

export const protobufPackage = "envoy.config.core.v3";

/**
 * Message type for extension configuration.
 * [#next-major-version: revisit all existing typed_config that doesn't use this wrapper.].
 */
export interface TypedExtensionConfig {
  /**
   * The name of an extension. This is not used to select the extension, instead
   * it serves the role of an opaque identifier.
   */
  name: string;
  /**
   * The typed config for the extension. The type URL will be used to identify
   * the extension. In the case that the type URL is ``xds.type.v3.TypedStruct``
   * (or, for historical reasons, ``udpa.type.v1.TypedStruct``), the inner type
   * URL of ``TypedStruct`` will be utilized. See the
   * :ref:`extension configuration overview
   * <config_overview_extension_configuration>` for further details.
   */
  typedConfig: Any | undefined;
}

function createBaseTypedExtensionConfig(): TypedExtensionConfig {
  return { name: "", typedConfig: undefined };
}

export const TypedExtensionConfig: MessageFns<TypedExtensionConfig> = {
  encode(message: TypedExtensionConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.typedConfig !== undefined) {
      Any.encode(message.typedConfig, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TypedExtensionConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTypedExtensionConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.typedConfig = Any.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TypedExtensionConfig {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      typedConfig: isSet(object.typedConfig) ? Any.fromJSON(object.typedConfig) : undefined,
    };
  },

  toJSON(message: TypedExtensionConfig): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.typedConfig !== undefined) {
      obj.typedConfig = Any.toJSON(message.typedConfig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TypedExtensionConfig>, I>>(base?: I): TypedExtensionConfig {
    return TypedExtensionConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TypedExtensionConfig>, I>>(object: I): TypedExtensionConfig {
    const message = createBaseTypedExtensionConfig();
    message.name = object.name ?? "";
    message.typedConfig = (object.typedConfig !== undefined && object.typedConfig !== null)
      ? Any.fromPartial(object.typedConfig)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
