// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: envoy/config/core/v3/socket_option.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "envoy.config.core.v3";

/**
 * Generic socket option message. This would be used to set socket options that
 * might not exist in upstream kernels or precompiled Envoy binaries.
 *
 * For example:
 *
 * .. code-block:: json
 *
 *  {
 *    "description": "support tcp keep alive",
 *    "state": 0,
 *    "level": 1,
 *    "name": 9,
 *    "int_value": 1,
 *  }
 *
 * 1 means SOL_SOCKET and 9 means SO_KEEPALIVE on Linux.
 * With the above configuration, `TCP Keep-Alives <https://www.freesoft.org/CIE/RFC/1122/114.htm>`_
 * can be enabled in socket with Linux, which can be used in
 * :ref:`listener's<envoy_v3_api_field_config.listener.v3.Listener.socket_options>` or
 * :ref:`admin's <envoy_v3_api_field_config.bootstrap.v3.Admin.socket_options>` socket_options etc.
 *
 * It should be noted that the name or level may have different values on different platforms.
 * [#next-free-field: 8]
 */
export interface SocketOption {
  /**
   * An optional name to give this socket option for debugging, etc.
   * Uniqueness is not required and no special meaning is assumed.
   */
  description: string;
  /** Corresponding to the level value passed to setsockopt, such as IPPROTO_TCP */
  level: string;
  /** The numeric name as passed to setsockopt */
  name: string;
  /** Because many sockopts take an int value. */
  intValue?:
    | string
    | undefined;
  /** Otherwise it's a byte buffer. */
  bufValue?:
    | Uint8Array
    | undefined;
  /**
   * The state in which the option will be applied. When used in BindConfig
   * STATE_PREBIND is currently the only valid value.
   */
  state: SocketOption_SocketState;
  /**
   * Apply the socket option to the specified `socket type <https://linux.die.net/man/2/socket>`_.
   * If not specified, the socket option will be applied to all socket types.
   */
  type: SocketOption_SocketType | undefined;
}

export enum SocketOption_SocketState {
  /** STATE_PREBIND - Socket options are applied after socket creation but before binding the socket to a port */
  STATE_PREBIND = 0,
  /** STATE_BOUND - Socket options are applied after binding the socket to a port but before calling listen() */
  STATE_BOUND = 1,
  /** STATE_LISTENING - Socket options are applied after calling listen() */
  STATE_LISTENING = 2,
  UNRECOGNIZED = -1,
}

export function socketOption_SocketStateFromJSON(object: any): SocketOption_SocketState {
  switch (object) {
    case 0:
    case "STATE_PREBIND":
      return SocketOption_SocketState.STATE_PREBIND;
    case 1:
    case "STATE_BOUND":
      return SocketOption_SocketState.STATE_BOUND;
    case 2:
    case "STATE_LISTENING":
      return SocketOption_SocketState.STATE_LISTENING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SocketOption_SocketState.UNRECOGNIZED;
  }
}

export function socketOption_SocketStateToJSON(object: SocketOption_SocketState): string {
  switch (object) {
    case SocketOption_SocketState.STATE_PREBIND:
      return "STATE_PREBIND";
    case SocketOption_SocketState.STATE_BOUND:
      return "STATE_BOUND";
    case SocketOption_SocketState.STATE_LISTENING:
      return "STATE_LISTENING";
    case SocketOption_SocketState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * The `socket type <https://linux.die.net/man/2/socket>`_ to apply the socket option to.
 * Only one field should be set. If multiple fields are set, the precedence order will determine
 * the selected one. If none of the fields is set, the socket option will be applied to all socket types.
 *
 * For example:
 * If :ref:`stream <envoy_v3_api_field_config.core.v3.SocketOption.SocketType.stream>` is set,
 * it takes precedence over :ref:`datagram <envoy_v3_api_field_config.core.v3.SocketOption.SocketType.datagram>`.
 */
export interface SocketOption_SocketType {
  /** Apply the socket option to the stream socket type. */
  stream:
    | SocketOption_SocketType_Stream
    | undefined;
  /** Apply the socket option to the datagram socket type. */
  datagram: SocketOption_SocketType_Datagram | undefined;
}

/** The stream socket type. */
export interface SocketOption_SocketType_Stream {
}

/** The datagram socket type. */
export interface SocketOption_SocketType_Datagram {
}

export interface SocketOptionsOverride {
  socketOptions: SocketOption[];
}

function createBaseSocketOption(): SocketOption {
  return {
    description: "",
    level: "0",
    name: "0",
    intValue: undefined,
    bufValue: undefined,
    state: 0,
    type: undefined,
  };
}

export const SocketOption: MessageFns<SocketOption> = {
  encode(message: SocketOption, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.description !== "") {
      writer.uint32(10).string(message.description);
    }
    if (message.level !== "0") {
      writer.uint32(16).int64(message.level);
    }
    if (message.name !== "0") {
      writer.uint32(24).int64(message.name);
    }
    if (message.intValue !== undefined) {
      writer.uint32(32).int64(message.intValue);
    }
    if (message.bufValue !== undefined) {
      writer.uint32(42).bytes(message.bufValue);
    }
    if (message.state !== 0) {
      writer.uint32(48).int32(message.state);
    }
    if (message.type !== undefined) {
      SocketOption_SocketType.encode(message.type, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SocketOption {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSocketOption();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.level = reader.int64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.name = reader.int64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.intValue = reader.int64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.bufValue = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.type = SocketOption_SocketType.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SocketOption {
    return {
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      level: isSet(object.level) ? globalThis.String(object.level) : "0",
      name: isSet(object.name) ? globalThis.String(object.name) : "0",
      intValue: isSet(object.intValue) ? globalThis.String(object.intValue) : undefined,
      bufValue: isSet(object.bufValue) ? bytesFromBase64(object.bufValue) : undefined,
      state: isSet(object.state) ? socketOption_SocketStateFromJSON(object.state) : 0,
      type: isSet(object.type) ? SocketOption_SocketType.fromJSON(object.type) : undefined,
    };
  },

  toJSON(message: SocketOption): unknown {
    const obj: any = {};
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.level !== "0") {
      obj.level = message.level;
    }
    if (message.name !== "0") {
      obj.name = message.name;
    }
    if (message.intValue !== undefined) {
      obj.intValue = message.intValue;
    }
    if (message.bufValue !== undefined) {
      obj.bufValue = base64FromBytes(message.bufValue);
    }
    if (message.state !== 0) {
      obj.state = socketOption_SocketStateToJSON(message.state);
    }
    if (message.type !== undefined) {
      obj.type = SocketOption_SocketType.toJSON(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SocketOption>, I>>(base?: I): SocketOption {
    return SocketOption.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SocketOption>, I>>(object: I): SocketOption {
    const message = createBaseSocketOption();
    message.description = object.description ?? "";
    message.level = object.level ?? "0";
    message.name = object.name ?? "0";
    message.intValue = object.intValue ?? undefined;
    message.bufValue = object.bufValue ?? undefined;
    message.state = object.state ?? 0;
    message.type = (object.type !== undefined && object.type !== null)
      ? SocketOption_SocketType.fromPartial(object.type)
      : undefined;
    return message;
  },
};

function createBaseSocketOption_SocketType(): SocketOption_SocketType {
  return { stream: undefined, datagram: undefined };
}

export const SocketOption_SocketType: MessageFns<SocketOption_SocketType> = {
  encode(message: SocketOption_SocketType, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stream !== undefined) {
      SocketOption_SocketType_Stream.encode(message.stream, writer.uint32(10).fork()).join();
    }
    if (message.datagram !== undefined) {
      SocketOption_SocketType_Datagram.encode(message.datagram, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SocketOption_SocketType {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSocketOption_SocketType();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stream = SocketOption_SocketType_Stream.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.datagram = SocketOption_SocketType_Datagram.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SocketOption_SocketType {
    return {
      stream: isSet(object.stream) ? SocketOption_SocketType_Stream.fromJSON(object.stream) : undefined,
      datagram: isSet(object.datagram) ? SocketOption_SocketType_Datagram.fromJSON(object.datagram) : undefined,
    };
  },

  toJSON(message: SocketOption_SocketType): unknown {
    const obj: any = {};
    if (message.stream !== undefined) {
      obj.stream = SocketOption_SocketType_Stream.toJSON(message.stream);
    }
    if (message.datagram !== undefined) {
      obj.datagram = SocketOption_SocketType_Datagram.toJSON(message.datagram);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SocketOption_SocketType>, I>>(base?: I): SocketOption_SocketType {
    return SocketOption_SocketType.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SocketOption_SocketType>, I>>(object: I): SocketOption_SocketType {
    const message = createBaseSocketOption_SocketType();
    message.stream = (object.stream !== undefined && object.stream !== null)
      ? SocketOption_SocketType_Stream.fromPartial(object.stream)
      : undefined;
    message.datagram = (object.datagram !== undefined && object.datagram !== null)
      ? SocketOption_SocketType_Datagram.fromPartial(object.datagram)
      : undefined;
    return message;
  },
};

function createBaseSocketOption_SocketType_Stream(): SocketOption_SocketType_Stream {
  return {};
}

export const SocketOption_SocketType_Stream: MessageFns<SocketOption_SocketType_Stream> = {
  encode(_: SocketOption_SocketType_Stream, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SocketOption_SocketType_Stream {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSocketOption_SocketType_Stream();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SocketOption_SocketType_Stream {
    return {};
  },

  toJSON(_: SocketOption_SocketType_Stream): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SocketOption_SocketType_Stream>, I>>(base?: I): SocketOption_SocketType_Stream {
    return SocketOption_SocketType_Stream.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SocketOption_SocketType_Stream>, I>>(_: I): SocketOption_SocketType_Stream {
    const message = createBaseSocketOption_SocketType_Stream();
    return message;
  },
};

function createBaseSocketOption_SocketType_Datagram(): SocketOption_SocketType_Datagram {
  return {};
}

export const SocketOption_SocketType_Datagram: MessageFns<SocketOption_SocketType_Datagram> = {
  encode(_: SocketOption_SocketType_Datagram, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SocketOption_SocketType_Datagram {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSocketOption_SocketType_Datagram();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SocketOption_SocketType_Datagram {
    return {};
  },

  toJSON(_: SocketOption_SocketType_Datagram): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SocketOption_SocketType_Datagram>, I>>(
    base?: I,
  ): SocketOption_SocketType_Datagram {
    return SocketOption_SocketType_Datagram.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SocketOption_SocketType_Datagram>, I>>(
    _: I,
  ): SocketOption_SocketType_Datagram {
    const message = createBaseSocketOption_SocketType_Datagram();
    return message;
  },
};

function createBaseSocketOptionsOverride(): SocketOptionsOverride {
  return { socketOptions: [] };
}

export const SocketOptionsOverride: MessageFns<SocketOptionsOverride> = {
  encode(message: SocketOptionsOverride, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.socketOptions) {
      SocketOption.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SocketOptionsOverride {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSocketOptionsOverride();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.socketOptions.push(SocketOption.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SocketOptionsOverride {
    return {
      socketOptions: globalThis.Array.isArray(object?.socketOptions)
        ? object.socketOptions.map((e: any) => SocketOption.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SocketOptionsOverride): unknown {
    const obj: any = {};
    if (message.socketOptions?.length) {
      obj.socketOptions = message.socketOptions.map((e) => SocketOption.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SocketOptionsOverride>, I>>(base?: I): SocketOptionsOverride {
    return SocketOptionsOverride.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SocketOptionsOverride>, I>>(object: I): SocketOptionsOverride {
    const message = createBaseSocketOptionsOverride();
    message.socketOptions = object.socketOptions?.map((e) => SocketOption.fromPartial(e)) || [];
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
