// THIS FILE IS DEPRECATED
// Users should instead use the corresponding proto in the xds tree.
// No new changes will be accepted here.

// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file udpa/annotations/migrate.proto (package udpa.annotations, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file udpa/annotations/migrate.proto.
 */
export const file_udpa_annotations_migrate: GenFile = /*@__PURE__*/
  fileDesc("Ch51ZHBhL2Fubm90YXRpb25zL21pZ3JhdGUucHJvdG8SEHVkcGEuYW5ub3RhdGlvbnMiMAoVRmlsZU1pZ3JhdGVBbm5vdGF0aW9uEhcKD21vdmVfdG9fcGFja2FnZRgCIAEoCUIpWidnaXRodWIuY29tL2NuY2YveGRzL2dvL3VkcGEvYW5ub3RhdGlvbnNiBnByb3RvMw");

/**
 * @generated from message udpa.annotations.FileMigrateAnnotation
 */
export type FileMigrateAnnotation = Message<"udpa.annotations.FileMigrateAnnotation"> & {
  /**
   * Move all types in the file to another package, this implies changing proto
   * file path.
   *
   * @generated from field: string move_to_package = 2;
   */
  moveToPackage: string;
};

/**
 * Describes the message udpa.annotations.FileMigrateAnnotation.
 * Use `create(FileMigrateAnnotationSchema)` to create a new message.
 */
export const FileMigrateAnnotationSchema: GenMessage<FileMigrateAnnotation> = /*@__PURE__*/
  messageDesc(file_udpa_annotations_migrate, 0);

