// THIS FILE IS DEPRECATED
// Users should instead use the corresponding proto in the xds tree.
// No new changes will be accepted here.

// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file udpa/annotations/status.proto (package udpa.annotations, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file udpa/annotations/status.proto.
 */
export const file_udpa_annotations_status: GenFile = /*@__PURE__*/
  fileDesc("Ch11ZHBhL2Fubm90YXRpb25zL3N0YXR1cy5wcm90bxIQdWRwYS5hbm5vdGF0aW9ucyJ0ChBTdGF0dXNBbm5vdGF0aW9uEhgKEHdvcmtfaW5fcHJvZ3Jlc3MYASABKAgSRgoWcGFja2FnZV92ZXJzaW9uX3N0YXR1cxgCIAEoDjImLnVkcGEuYW5ub3RhdGlvbnMuUGFja2FnZVZlcnNpb25TdGF0dXMqXQoUUGFja2FnZVZlcnNpb25TdGF0dXMSCwoHVU5LTk9XThAAEgoKBkZST1pFThABEgoKBkFDVElWRRACEiAKHE5FWFRfTUFKT1JfVkVSU0lPTl9DQU5ESURBVEUQA0IpWidnaXRodWIuY29tL2NuY2YveGRzL2dvL3VkcGEvYW5ub3RhdGlvbnNiBnByb3RvMw");

/**
 * @generated from message udpa.annotations.StatusAnnotation
 */
export type StatusAnnotation = Message<"udpa.annotations.StatusAnnotation"> & {
  /**
   * The entity is work-in-progress and subject to breaking changes.
   *
   * @generated from field: bool work_in_progress = 1;
   */
  workInProgress: boolean;

  /**
   * The entity belongs to a package with the given version status.
   *
   * @generated from field: udpa.annotations.PackageVersionStatus package_version_status = 2;
   */
  packageVersionStatus: PackageVersionStatus;
};

/**
 * Describes the message udpa.annotations.StatusAnnotation.
 * Use `create(StatusAnnotationSchema)` to create a new message.
 */
export const StatusAnnotationSchema: GenMessage<StatusAnnotation> = /*@__PURE__*/
  messageDesc(file_udpa_annotations_status, 0);

/**
 * @generated from enum udpa.annotations.PackageVersionStatus
 */
export enum PackageVersionStatus {
  /**
   * Unknown package version status.
   *
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * This version of the package is frozen.
   *
   * @generated from enum value: FROZEN = 1;
   */
  FROZEN = 1,

  /**
   * This version of the package is the active development version.
   *
   * @generated from enum value: ACTIVE = 2;
   */
  ACTIVE = 2,

  /**
   * This version of the package is the candidate for the next major version. It
   * is typically machine generated from the active development version.
   *
   * @generated from enum value: NEXT_MAJOR_VERSION_CANDIDATE = 3;
   */
  NEXT_MAJOR_VERSION_CANDIDATE = 3,
}

/**
 * Describes the enum udpa.annotations.PackageVersionStatus.
 */
export const PackageVersionStatusSchema: GenEnum<PackageVersionStatus> = /*@__PURE__*/
  enumDesc(file_udpa_annotations_status, 0);

