// THIS FILE IS DEPRECATED
// Users should instead use the corresponding proto in the xds tree.
// No new changes will be accepted here.

// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file udpa/annotations/versioning.proto (package udpa.annotations, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file udpa/annotations/versioning.proto.
 */
export const file_udpa_annotations_versioning: GenFile = /*@__PURE__*/
  fileDesc("CiF1ZHBhL2Fubm90YXRpb25zL3ZlcnNpb25pbmcucHJvdG8SEHVkcGEuYW5ub3RhdGlvbnMiNQoUVmVyc2lvbmluZ0Fubm90YXRpb24SHQoVcHJldmlvdXNfbWVzc2FnZV90eXBlGAEgASgJQilaJ2dpdGh1Yi5jb20vY25jZi94ZHMvZ28vdWRwYS9hbm5vdGF0aW9uc2IGcHJvdG8z");

/**
 * @generated from message udpa.annotations.VersioningAnnotation
 */
export type VersioningAnnotation = Message<"udpa.annotations.VersioningAnnotation"> & {
  /**
   * Track the previous message type. E.g. this message might be
   * udpa.foo.v3alpha.Foo and it was previously udpa.bar.v2.Bar. This
   * information is consumed by UDPA via proto descriptors.
   *
   * @generated from field: string previous_message_type = 1;
   */
  previousMessageType: string;
};

/**
 * Describes the message udpa.annotations.VersioningAnnotation.
 * Use `create(VersioningAnnotationSchema)` to create a new message.
 */
export const VersioningAnnotationSchema: GenMessage<VersioningAnnotation> = /*@__PURE__*/
  messageDesc(file_udpa_annotations_versioning, 0);

