// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: udpa/annotations/versioning.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "udpa.annotations";

export interface VersioningAnnotation {
  /**
   * Track the previous message type. E.g. this message might be
   * udpa.foo.v3alpha.Foo and it was previously udpa.bar.v2.Bar. This
   * information is consumed by UDPA via proto descriptors.
   */
  previousMessageType: string;
}

function createBaseVersioningAnnotation(): VersioningAnnotation {
  return { previousMessageType: "" };
}

export const VersioningAnnotation: MessageFns<VersioningAnnotation> = {
  encode(message: VersioningAnnotation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.previousMessageType !== "") {
      writer.uint32(10).string(message.previousMessageType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VersioningAnnotation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVersioningAnnotation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.previousMessageType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VersioningAnnotation {
    return {
      previousMessageType: isSet(object.previousMessageType) ? globalThis.String(object.previousMessageType) : "",
    };
  },

  toJSON(message: VersioningAnnotation): unknown {
    const obj: any = {};
    if (message.previousMessageType !== "") {
      obj.previousMessageType = message.previousMessageType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VersioningAnnotation>, I>>(base?: I): VersioningAnnotation {
    return VersioningAnnotation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VersioningAnnotation>, I>>(object: I): VersioningAnnotation {
    const message = createBaseVersioningAnnotation();
    message.previousMessageType = object.previousMessageType ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
