// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: xds/annotations/v3/status.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "xds.annotations.v3";

export enum PackageVersionStatus {
  /** UNKNOWN - Unknown package version status. */
  UNKNOWN = 0,
  /** FROZEN - This version of the package is frozen. */
  FROZEN = 1,
  /** ACTIVE - This version of the package is the active development version. */
  ACTIVE = 2,
  /**
   * NEXT_MAJOR_VERSION_CANDIDATE - This version of the package is the candidate for the next major version. It
   * is typically machine generated from the active development version.
   */
  NEXT_MAJOR_VERSION_CANDIDATE = 3,
  UNRECOGNIZED = -1,
}

export function packageVersionStatusFromJSON(object: any): PackageVersionStatus {
  switch (object) {
    case 0:
    case "UNKNOWN":
      return PackageVersionStatus.UNKNOWN;
    case 1:
    case "FROZEN":
      return PackageVersionStatus.FROZEN;
    case 2:
    case "ACTIVE":
      return PackageVersionStatus.ACTIVE;
    case 3:
    case "NEXT_MAJOR_VERSION_CANDIDATE":
      return PackageVersionStatus.NEXT_MAJOR_VERSION_CANDIDATE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PackageVersionStatus.UNRECOGNIZED;
  }
}

export function packageVersionStatusToJSON(object: PackageVersionStatus): string {
  switch (object) {
    case PackageVersionStatus.UNKNOWN:
      return "UNKNOWN";
    case PackageVersionStatus.FROZEN:
      return "FROZEN";
    case PackageVersionStatus.ACTIVE:
      return "ACTIVE";
    case PackageVersionStatus.NEXT_MAJOR_VERSION_CANDIDATE:
      return "NEXT_MAJOR_VERSION_CANDIDATE";
    case PackageVersionStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface FileStatusAnnotation {
  /** The entity is work-in-progress and subject to breaking changes. */
  workInProgress: boolean;
}

export interface MessageStatusAnnotation {
  /** The entity is work-in-progress and subject to breaking changes. */
  workInProgress: boolean;
}

export interface FieldStatusAnnotation {
  /** The entity is work-in-progress and subject to breaking changes. */
  workInProgress: boolean;
}

export interface StatusAnnotation {
  /** The entity is work-in-progress and subject to breaking changes. */
  workInProgress: boolean;
  /** The entity belongs to a package with the given version status. */
  packageVersionStatus: PackageVersionStatus;
}

function createBaseFileStatusAnnotation(): FileStatusAnnotation {
  return { workInProgress: false };
}

export const FileStatusAnnotation: MessageFns<FileStatusAnnotation> = {
  encode(message: FileStatusAnnotation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workInProgress !== false) {
      writer.uint32(8).bool(message.workInProgress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileStatusAnnotation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileStatusAnnotation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.workInProgress = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FileStatusAnnotation {
    return { workInProgress: isSet(object.workInProgress) ? globalThis.Boolean(object.workInProgress) : false };
  },

  toJSON(message: FileStatusAnnotation): unknown {
    const obj: any = {};
    if (message.workInProgress !== false) {
      obj.workInProgress = message.workInProgress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FileStatusAnnotation>, I>>(base?: I): FileStatusAnnotation {
    return FileStatusAnnotation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FileStatusAnnotation>, I>>(object: I): FileStatusAnnotation {
    const message = createBaseFileStatusAnnotation();
    message.workInProgress = object.workInProgress ?? false;
    return message;
  },
};

function createBaseMessageStatusAnnotation(): MessageStatusAnnotation {
  return { workInProgress: false };
}

export const MessageStatusAnnotation: MessageFns<MessageStatusAnnotation> = {
  encode(message: MessageStatusAnnotation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workInProgress !== false) {
      writer.uint32(8).bool(message.workInProgress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageStatusAnnotation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageStatusAnnotation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.workInProgress = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MessageStatusAnnotation {
    return { workInProgress: isSet(object.workInProgress) ? globalThis.Boolean(object.workInProgress) : false };
  },

  toJSON(message: MessageStatusAnnotation): unknown {
    const obj: any = {};
    if (message.workInProgress !== false) {
      obj.workInProgress = message.workInProgress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MessageStatusAnnotation>, I>>(base?: I): MessageStatusAnnotation {
    return MessageStatusAnnotation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessageStatusAnnotation>, I>>(object: I): MessageStatusAnnotation {
    const message = createBaseMessageStatusAnnotation();
    message.workInProgress = object.workInProgress ?? false;
    return message;
  },
};

function createBaseFieldStatusAnnotation(): FieldStatusAnnotation {
  return { workInProgress: false };
}

export const FieldStatusAnnotation: MessageFns<FieldStatusAnnotation> = {
  encode(message: FieldStatusAnnotation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workInProgress !== false) {
      writer.uint32(8).bool(message.workInProgress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FieldStatusAnnotation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFieldStatusAnnotation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.workInProgress = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FieldStatusAnnotation {
    return { workInProgress: isSet(object.workInProgress) ? globalThis.Boolean(object.workInProgress) : false };
  },

  toJSON(message: FieldStatusAnnotation): unknown {
    const obj: any = {};
    if (message.workInProgress !== false) {
      obj.workInProgress = message.workInProgress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FieldStatusAnnotation>, I>>(base?: I): FieldStatusAnnotation {
    return FieldStatusAnnotation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FieldStatusAnnotation>, I>>(object: I): FieldStatusAnnotation {
    const message = createBaseFieldStatusAnnotation();
    message.workInProgress = object.workInProgress ?? false;
    return message;
  },
};

function createBaseStatusAnnotation(): StatusAnnotation {
  return { workInProgress: false, packageVersionStatus: 0 };
}

export const StatusAnnotation: MessageFns<StatusAnnotation> = {
  encode(message: StatusAnnotation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workInProgress !== false) {
      writer.uint32(8).bool(message.workInProgress);
    }
    if (message.packageVersionStatus !== 0) {
      writer.uint32(16).int32(message.packageVersionStatus);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatusAnnotation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatusAnnotation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.workInProgress = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.packageVersionStatus = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StatusAnnotation {
    return {
      workInProgress: isSet(object.workInProgress) ? globalThis.Boolean(object.workInProgress) : false,
      packageVersionStatus: isSet(object.packageVersionStatus)
        ? packageVersionStatusFromJSON(object.packageVersionStatus)
        : 0,
    };
  },

  toJSON(message: StatusAnnotation): unknown {
    const obj: any = {};
    if (message.workInProgress !== false) {
      obj.workInProgress = message.workInProgress;
    }
    if (message.packageVersionStatus !== 0) {
      obj.packageVersionStatus = packageVersionStatusToJSON(message.packageVersionStatus);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StatusAnnotation>, I>>(base?: I): StatusAnnotation {
    return StatusAnnotation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StatusAnnotation>, I>>(object: I): StatusAnnotation {
    const message = createBaseStatusAnnotation();
    message.workInProgress = object.workInProgress ?? false;
    message.packageVersionStatus = object.packageVersionStatus ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
