// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file xds/annotations/v3/status.proto (package xds.annotations.v3, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file xds/annotations/v3/status.proto.
 */
export const file_xds_annotations_v3_status: GenFile = /*@__PURE__*/
  fileDesc("Ch94ZHMvYW5ub3RhdGlvbnMvdjMvc3RhdHVzLnByb3RvEhJ4ZHMuYW5ub3RhdGlvbnMudjMidgoQU3RhdHVzQW5ub3RhdGlvbhIYChB3b3JrX2luX3Byb2dyZXNzGAEgASgIEkgKFnBhY2thZ2VfdmVyc2lvbl9zdGF0dXMYAiABKA4yKC54ZHMuYW5ub3RhdGlvbnMudjMuUGFja2FnZVZlcnNpb25TdGF0dXMqXQoUUGFja2FnZVZlcnNpb25TdGF0dXMSCwoHVU5LTk9XThAAEgoKBkZST1pFThABEgoKBkFDVElWRRACEiAKHE5FWFRfTUFKT1JfVkVSU0lPTl9DQU5ESURBVEUQA0IrWilnaXRodWIuY29tL2NuY2YveGRzL2dvL3hkcy9hbm5vdGF0aW9ucy92M2IGcHJvdG8z");

/**
 * @generated from message xds.annotations.v3.StatusAnnotation
 */
export type StatusAnnotation = Message<"xds.annotations.v3.StatusAnnotation"> & {
  /**
   * The entity is work-in-progress and subject to breaking changes.
   *
   * @generated from field: bool work_in_progress = 1;
   */
  workInProgress: boolean;

  /**
   * The entity belongs to a package with the given version status.
   *
   * @generated from field: xds.annotations.v3.PackageVersionStatus package_version_status = 2;
   */
  packageVersionStatus: PackageVersionStatus;
};

/**
 * Describes the message xds.annotations.v3.StatusAnnotation.
 * Use `create(StatusAnnotationSchema)` to create a new message.
 */
export const StatusAnnotationSchema: GenMessage<StatusAnnotation> = /*@__PURE__*/
  messageDesc(file_xds_annotations_v3_status, 0);

/**
 * @generated from enum xds.annotations.v3.PackageVersionStatus
 */
export enum PackageVersionStatus {
  /**
   * Unknown package version status.
   *
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * This version of the package is frozen.
   *
   * @generated from enum value: FROZEN = 1;
   */
  FROZEN = 1,

  /**
   * This version of the package is the active development version.
   *
   * @generated from enum value: ACTIVE = 2;
   */
  ACTIVE = 2,

  /**
   * This version of the package is the candidate for the next major version. It
   * is typically machine generated from the active development version.
   *
   * @generated from enum value: NEXT_MAJOR_VERSION_CANDIDATE = 3;
   */
  NEXT_MAJOR_VERSION_CANDIDATE = 3,
}

/**
 * Describes the enum xds.annotations.v3.PackageVersionStatus.
 */
export const PackageVersionStatusSchema: GenEnum<PackageVersionStatus> = /*@__PURE__*/
  enumDesc(file_xds_annotations_v3_status, 0);

