// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file envoy/annotations/deprecation.proto (package envoy.annotations, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import type { FieldOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file envoy/annotations/deprecation.proto.
 */
export const file_envoy_annotations_deprecation: GenFile = /*@__PURE__*/
  fileDesc("CiNlbnZveS9hbm5vdGF0aW9ucy9kZXByZWNhdGlvbi5wcm90bxIRZW52b3kuYW5ub3RhdGlvbnM6XwobZGVwcmVjYXRlZF9hdF9taW5vcl92ZXJzaW9uEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxjy6IBLIAEoCVIYZGVwcmVjYXRlZEF0TWlub3JWZXJzaW9uQjpaOGdpdGh1Yi5jb20vZW52b3lwcm94eS9nby1jb250cm9sLXBsYW5lL2Vudm95L2Fubm90YXRpb25zYgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * The API major and minor version on which the field was deprecated
 * (e.g., "3.5" for major version 3 and minor version 5).
 *
 * @generated from extension: string deprecated_at_minor_version = 157299826;
 */
export const deprecated_at_minor_version: GenExtension<FieldOptions, string> = /*@__PURE__*/
  extDesc(file_envoy_annotations_deprecation, 0);

