// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: envoy/annotations/deprecation.proto

/* eslint-disable */

export const protobufPackage = "envoy.annotations";
