// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: envoy/type/v3/http_status.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "envoy.type.v3";

/**
 * HTTP response codes supported in Envoy.
 * For more details: https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
 */
export enum StatusCode {
  /**
   * Empty - Empty - This code not part of the HTTP status code specification, but it is needed for proto
   * `enum` type.
   */
  Empty = 0,
  /** Continue - Continue - ``100`` status code. */
  Continue = 100,
  /** OK - OK - ``200`` status code. */
  OK = 200,
  /** Created - Created - ``201`` status code. */
  Created = 201,
  /** Accepted - Accepted - ``202`` status code. */
  Accepted = 202,
  /** NonAuthoritativeInformation - NonAuthoritativeInformation - ``203`` status code. */
  NonAuthoritativeInformation = 203,
  /** NoContent - NoContent - ``204`` status code. */
  NoContent = 204,
  /** ResetContent - ResetContent - ``205`` status code. */
  ResetContent = 205,
  /** PartialContent - PartialContent - ``206`` status code. */
  PartialContent = 206,
  /** MultiStatus - MultiStatus - ``207`` status code. */
  MultiStatus = 207,
  /** AlreadyReported - AlreadyReported - ``208`` status code. */
  AlreadyReported = 208,
  /** IMUsed - IMUsed - ``226`` status code. */
  IMUsed = 226,
  /** MultipleChoices - MultipleChoices - ``300`` status code. */
  MultipleChoices = 300,
  /** MovedPermanently - MovedPermanently - ``301`` status code. */
  MovedPermanently = 301,
  /** Found - Found - ``302`` status code. */
  Found = 302,
  /** SeeOther - SeeOther - ``303`` status code. */
  SeeOther = 303,
  /** NotModified - NotModified - ``304`` status code. */
  NotModified = 304,
  /** UseProxy - UseProxy - ``305`` status code. */
  UseProxy = 305,
  /** TemporaryRedirect - TemporaryRedirect - ``307`` status code. */
  TemporaryRedirect = 307,
  /** PermanentRedirect - PermanentRedirect - ``308`` status code. */
  PermanentRedirect = 308,
  /** BadRequest - BadRequest - ``400`` status code. */
  BadRequest = 400,
  /** Unauthorized - Unauthorized - ``401`` status code. */
  Unauthorized = 401,
  /** PaymentRequired - PaymentRequired - ``402`` status code. */
  PaymentRequired = 402,
  /** Forbidden - Forbidden - ``403`` status code. */
  Forbidden = 403,
  /** NotFound - NotFound - ``404`` status code. */
  NotFound = 404,
  /** MethodNotAllowed - MethodNotAllowed - ``405`` status code. */
  MethodNotAllowed = 405,
  /** NotAcceptable - NotAcceptable - ``406`` status code. */
  NotAcceptable = 406,
  /** ProxyAuthenticationRequired - ProxyAuthenticationRequired - ``407`` status code. */
  ProxyAuthenticationRequired = 407,
  /** RequestTimeout - RequestTimeout - ``408`` status code. */
  RequestTimeout = 408,
  /** Conflict - Conflict - ``409`` status code. */
  Conflict = 409,
  /** Gone - Gone - ``410`` status code. */
  Gone = 410,
  /** LengthRequired - LengthRequired - ``411`` status code. */
  LengthRequired = 411,
  /** PreconditionFailed - PreconditionFailed - ``412`` status code. */
  PreconditionFailed = 412,
  /** PayloadTooLarge - PayloadTooLarge - ``413`` status code. */
  PayloadTooLarge = 413,
  /** URITooLong - URITooLong - ``414`` status code. */
  URITooLong = 414,
  /** UnsupportedMediaType - UnsupportedMediaType - ``415`` status code. */
  UnsupportedMediaType = 415,
  /** RangeNotSatisfiable - RangeNotSatisfiable - ``416`` status code. */
  RangeNotSatisfiable = 416,
  /** ExpectationFailed - ExpectationFailed - ``417`` status code. */
  ExpectationFailed = 417,
  /** MisdirectedRequest - MisdirectedRequest - ``421`` status code. */
  MisdirectedRequest = 421,
  /** UnprocessableEntity - UnprocessableEntity - ``422`` status code. */
  UnprocessableEntity = 422,
  /** Locked - Locked - ``423`` status code. */
  Locked = 423,
  /** FailedDependency - FailedDependency - ``424`` status code. */
  FailedDependency = 424,
  /** UpgradeRequired - UpgradeRequired - ``426`` status code. */
  UpgradeRequired = 426,
  /** PreconditionRequired - PreconditionRequired - ``428`` status code. */
  PreconditionRequired = 428,
  /** TooManyRequests - TooManyRequests - ``429`` status code. */
  TooManyRequests = 429,
  /** RequestHeaderFieldsTooLarge - RequestHeaderFieldsTooLarge - ``431`` status code. */
  RequestHeaderFieldsTooLarge = 431,
  /** InternalServerError - InternalServerError - ``500`` status code. */
  InternalServerError = 500,
  /** NotImplemented - NotImplemented - ``501`` status code. */
  NotImplemented = 501,
  /** BadGateway - BadGateway - ``502`` status code. */
  BadGateway = 502,
  /** ServiceUnavailable - ServiceUnavailable - ``503`` status code. */
  ServiceUnavailable = 503,
  /** GatewayTimeout - GatewayTimeout - ``504`` status code. */
  GatewayTimeout = 504,
  /** HTTPVersionNotSupported - HTTPVersionNotSupported - ``505`` status code. */
  HTTPVersionNotSupported = 505,
  /** VariantAlsoNegotiates - VariantAlsoNegotiates - ``506`` status code. */
  VariantAlsoNegotiates = 506,
  /** InsufficientStorage - InsufficientStorage - ``507`` status code. */
  InsufficientStorage = 507,
  /** LoopDetected - LoopDetected - ``508`` status code. */
  LoopDetected = 508,
  /** NotExtended - NotExtended - ``510`` status code. */
  NotExtended = 510,
  /** NetworkAuthenticationRequired - NetworkAuthenticationRequired - ``511`` status code. */
  NetworkAuthenticationRequired = 511,
  UNRECOGNIZED = -1,
}

export function statusCodeFromJSON(object: any): StatusCode {
  switch (object) {
    case 0:
    case "Empty":
      return StatusCode.Empty;
    case 100:
    case "Continue":
      return StatusCode.Continue;
    case 200:
    case "OK":
      return StatusCode.OK;
    case 201:
    case "Created":
      return StatusCode.Created;
    case 202:
    case "Accepted":
      return StatusCode.Accepted;
    case 203:
    case "NonAuthoritativeInformation":
      return StatusCode.NonAuthoritativeInformation;
    case 204:
    case "NoContent":
      return StatusCode.NoContent;
    case 205:
    case "ResetContent":
      return StatusCode.ResetContent;
    case 206:
    case "PartialContent":
      return StatusCode.PartialContent;
    case 207:
    case "MultiStatus":
      return StatusCode.MultiStatus;
    case 208:
    case "AlreadyReported":
      return StatusCode.AlreadyReported;
    case 226:
    case "IMUsed":
      return StatusCode.IMUsed;
    case 300:
    case "MultipleChoices":
      return StatusCode.MultipleChoices;
    case 301:
    case "MovedPermanently":
      return StatusCode.MovedPermanently;
    case 302:
    case "Found":
      return StatusCode.Found;
    case 303:
    case "SeeOther":
      return StatusCode.SeeOther;
    case 304:
    case "NotModified":
      return StatusCode.NotModified;
    case 305:
    case "UseProxy":
      return StatusCode.UseProxy;
    case 307:
    case "TemporaryRedirect":
      return StatusCode.TemporaryRedirect;
    case 308:
    case "PermanentRedirect":
      return StatusCode.PermanentRedirect;
    case 400:
    case "BadRequest":
      return StatusCode.BadRequest;
    case 401:
    case "Unauthorized":
      return StatusCode.Unauthorized;
    case 402:
    case "PaymentRequired":
      return StatusCode.PaymentRequired;
    case 403:
    case "Forbidden":
      return StatusCode.Forbidden;
    case 404:
    case "NotFound":
      return StatusCode.NotFound;
    case 405:
    case "MethodNotAllowed":
      return StatusCode.MethodNotAllowed;
    case 406:
    case "NotAcceptable":
      return StatusCode.NotAcceptable;
    case 407:
    case "ProxyAuthenticationRequired":
      return StatusCode.ProxyAuthenticationRequired;
    case 408:
    case "RequestTimeout":
      return StatusCode.RequestTimeout;
    case 409:
    case "Conflict":
      return StatusCode.Conflict;
    case 410:
    case "Gone":
      return StatusCode.Gone;
    case 411:
    case "LengthRequired":
      return StatusCode.LengthRequired;
    case 412:
    case "PreconditionFailed":
      return StatusCode.PreconditionFailed;
    case 413:
    case "PayloadTooLarge":
      return StatusCode.PayloadTooLarge;
    case 414:
    case "URITooLong":
      return StatusCode.URITooLong;
    case 415:
    case "UnsupportedMediaType":
      return StatusCode.UnsupportedMediaType;
    case 416:
    case "RangeNotSatisfiable":
      return StatusCode.RangeNotSatisfiable;
    case 417:
    case "ExpectationFailed":
      return StatusCode.ExpectationFailed;
    case 421:
    case "MisdirectedRequest":
      return StatusCode.MisdirectedRequest;
    case 422:
    case "UnprocessableEntity":
      return StatusCode.UnprocessableEntity;
    case 423:
    case "Locked":
      return StatusCode.Locked;
    case 424:
    case "FailedDependency":
      return StatusCode.FailedDependency;
    case 426:
    case "UpgradeRequired":
      return StatusCode.UpgradeRequired;
    case 428:
    case "PreconditionRequired":
      return StatusCode.PreconditionRequired;
    case 429:
    case "TooManyRequests":
      return StatusCode.TooManyRequests;
    case 431:
    case "RequestHeaderFieldsTooLarge":
      return StatusCode.RequestHeaderFieldsTooLarge;
    case 500:
    case "InternalServerError":
      return StatusCode.InternalServerError;
    case 501:
    case "NotImplemented":
      return StatusCode.NotImplemented;
    case 502:
    case "BadGateway":
      return StatusCode.BadGateway;
    case 503:
    case "ServiceUnavailable":
      return StatusCode.ServiceUnavailable;
    case 504:
    case "GatewayTimeout":
      return StatusCode.GatewayTimeout;
    case 505:
    case "HTTPVersionNotSupported":
      return StatusCode.HTTPVersionNotSupported;
    case 506:
    case "VariantAlsoNegotiates":
      return StatusCode.VariantAlsoNegotiates;
    case 507:
    case "InsufficientStorage":
      return StatusCode.InsufficientStorage;
    case 508:
    case "LoopDetected":
      return StatusCode.LoopDetected;
    case 510:
    case "NotExtended":
      return StatusCode.NotExtended;
    case 511:
    case "NetworkAuthenticationRequired":
      return StatusCode.NetworkAuthenticationRequired;
    case -1:
    case "UNRECOGNIZED":
    default:
      return StatusCode.UNRECOGNIZED;
  }
}

export function statusCodeToJSON(object: StatusCode): string {
  switch (object) {
    case StatusCode.Empty:
      return "Empty";
    case StatusCode.Continue:
      return "Continue";
    case StatusCode.OK:
      return "OK";
    case StatusCode.Created:
      return "Created";
    case StatusCode.Accepted:
      return "Accepted";
    case StatusCode.NonAuthoritativeInformation:
      return "NonAuthoritativeInformation";
    case StatusCode.NoContent:
      return "NoContent";
    case StatusCode.ResetContent:
      return "ResetContent";
    case StatusCode.PartialContent:
      return "PartialContent";
    case StatusCode.MultiStatus:
      return "MultiStatus";
    case StatusCode.AlreadyReported:
      return "AlreadyReported";
    case StatusCode.IMUsed:
      return "IMUsed";
    case StatusCode.MultipleChoices:
      return "MultipleChoices";
    case StatusCode.MovedPermanently:
      return "MovedPermanently";
    case StatusCode.Found:
      return "Found";
    case StatusCode.SeeOther:
      return "SeeOther";
    case StatusCode.NotModified:
      return "NotModified";
    case StatusCode.UseProxy:
      return "UseProxy";
    case StatusCode.TemporaryRedirect:
      return "TemporaryRedirect";
    case StatusCode.PermanentRedirect:
      return "PermanentRedirect";
    case StatusCode.BadRequest:
      return "BadRequest";
    case StatusCode.Unauthorized:
      return "Unauthorized";
    case StatusCode.PaymentRequired:
      return "PaymentRequired";
    case StatusCode.Forbidden:
      return "Forbidden";
    case StatusCode.NotFound:
      return "NotFound";
    case StatusCode.MethodNotAllowed:
      return "MethodNotAllowed";
    case StatusCode.NotAcceptable:
      return "NotAcceptable";
    case StatusCode.ProxyAuthenticationRequired:
      return "ProxyAuthenticationRequired";
    case StatusCode.RequestTimeout:
      return "RequestTimeout";
    case StatusCode.Conflict:
      return "Conflict";
    case StatusCode.Gone:
      return "Gone";
    case StatusCode.LengthRequired:
      return "LengthRequired";
    case StatusCode.PreconditionFailed:
      return "PreconditionFailed";
    case StatusCode.PayloadTooLarge:
      return "PayloadTooLarge";
    case StatusCode.URITooLong:
      return "URITooLong";
    case StatusCode.UnsupportedMediaType:
      return "UnsupportedMediaType";
    case StatusCode.RangeNotSatisfiable:
      return "RangeNotSatisfiable";
    case StatusCode.ExpectationFailed:
      return "ExpectationFailed";
    case StatusCode.MisdirectedRequest:
      return "MisdirectedRequest";
    case StatusCode.UnprocessableEntity:
      return "UnprocessableEntity";
    case StatusCode.Locked:
      return "Locked";
    case StatusCode.FailedDependency:
      return "FailedDependency";
    case StatusCode.UpgradeRequired:
      return "UpgradeRequired";
    case StatusCode.PreconditionRequired:
      return "PreconditionRequired";
    case StatusCode.TooManyRequests:
      return "TooManyRequests";
    case StatusCode.RequestHeaderFieldsTooLarge:
      return "RequestHeaderFieldsTooLarge";
    case StatusCode.InternalServerError:
      return "InternalServerError";
    case StatusCode.NotImplemented:
      return "NotImplemented";
    case StatusCode.BadGateway:
      return "BadGateway";
    case StatusCode.ServiceUnavailable:
      return "ServiceUnavailable";
    case StatusCode.GatewayTimeout:
      return "GatewayTimeout";
    case StatusCode.HTTPVersionNotSupported:
      return "HTTPVersionNotSupported";
    case StatusCode.VariantAlsoNegotiates:
      return "VariantAlsoNegotiates";
    case StatusCode.InsufficientStorage:
      return "InsufficientStorage";
    case StatusCode.LoopDetected:
      return "LoopDetected";
    case StatusCode.NotExtended:
      return "NotExtended";
    case StatusCode.NetworkAuthenticationRequired:
      return "NetworkAuthenticationRequired";
    case StatusCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** HTTP status. */
export interface HttpStatus {
  /** Supplies HTTP response code. */
  code: StatusCode;
}

function createBaseHttpStatus(): HttpStatus {
  return { code: 0 };
}

export const HttpStatus: MessageFns<HttpStatus> = {
  encode(message: HttpStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HttpStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHttpStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HttpStatus {
    return { code: isSet(object.code) ? statusCodeFromJSON(object.code) : 0 };
  },

  toJSON(message: HttpStatus): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = statusCodeToJSON(message.code);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HttpStatus>, I>>(base?: I): HttpStatus {
    return HttpStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HttpStatus>, I>>(object: I): HttpStatus {
    const message = createBaseHttpStatus();
    message.code = object.code ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
