// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: envoy/type/v3/semantic_version.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "envoy.type.v3";

/**
 * Envoy uses SemVer (https://semver.org/). Major/minor versions indicate
 * expected behaviors and APIs, the patch version field is used only
 * for security fixes and can be generally ignored.
 */
export interface SemanticVersion {
  majorNumber: number;
  minorNumber: number;
  patch: number;
}

function createBaseSemanticVersion(): SemanticVersion {
  return { majorNumber: 0, minorNumber: 0, patch: 0 };
}

export const SemanticVersion: MessageFns<SemanticVersion> = {
  encode(message: SemanticVersion, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.majorNumber !== 0) {
      writer.uint32(8).uint32(message.majorNumber);
    }
    if (message.minorNumber !== 0) {
      writer.uint32(16).uint32(message.minorNumber);
    }
    if (message.patch !== 0) {
      writer.uint32(24).uint32(message.patch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SemanticVersion {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSemanticVersion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.majorNumber = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.minorNumber = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.patch = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SemanticVersion {
    return {
      majorNumber: isSet(object.majorNumber) ? globalThis.Number(object.majorNumber) : 0,
      minorNumber: isSet(object.minorNumber) ? globalThis.Number(object.minorNumber) : 0,
      patch: isSet(object.patch) ? globalThis.Number(object.patch) : 0,
    };
  },

  toJSON(message: SemanticVersion): unknown {
    const obj: any = {};
    if (message.majorNumber !== 0) {
      obj.majorNumber = Math.round(message.majorNumber);
    }
    if (message.minorNumber !== 0) {
      obj.minorNumber = Math.round(message.minorNumber);
    }
    if (message.patch !== 0) {
      obj.patch = Math.round(message.patch);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SemanticVersion>, I>>(base?: I): SemanticVersion {
    return SemanticVersion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SemanticVersion>, I>>(object: I): SemanticVersion {
    const message = createBaseSemanticVersion();
    message.majorNumber = object.majorNumber ?? 0;
    message.minorNumber = object.minorNumber ?? 0;
    message.patch = object.patch ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
